<?php
global $cjsupport_item_options, $cjsupport_email_messages;

$email_messages_file = cjsupport_item_path('item_dir').'/modules/functions/email-messages.php';
require_once($email_messages_file);

$enable_disable_array = array(
	'enable' => __('Enable', 'cjsupport'),
	'disable' => __('Disable', 'cjsupport'),
);

$cjsupport_item_options['cjsupport_emails_new_user'] = array(
	array(
		'type' => 'heading',
		'id' => 'cjsupport_emails_new_user_heading',
		'label' => '',
		'info' => '',
		'suffix' => '',
		'prefix' => '',
		'default' => __('New User Email Message', 'cjsupport'),
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	),
	array(
		'type' => 'info-full',
		'id' => 'cjsupport_emails_new_user_info',
		'label' => '',
		'info' => '',
		'suffix' => '',
		'prefix' => '',
		'default' => __('<p>When a new customer sends an email to IMAP mailbox, a new user account is created if system does not found the email in users table. This messsage will be sent to new user with his account details.</p>', 'cjsupport'),
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	),
	array(
		'type' => 'text',
		'id' => 'new_user_subject_to_client',
		'label' => __('Email Subject', 'cjsupport'),
		'info' => '<p>You can use following variables in the message.</p>
				   <p><code>%%site_name%%</code> : This will be replaced with your website name saved under General Settings.</p>',
		'suffix' => '',
		'prefix' => '',
		'default' => $cjsupport_email_messages['new_user_subject_to_client'],
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	),
	array(
		'type' => 'wysiwyg',
		'id' => 'new_user_message_to_client',
		'label' => __('Email Message', 'cjsupport'),
		'info' => '<p>You can use following variables in the message.</p>
				<p><code>%%user_login%%</code> : This will be replaced with username.</p>
				<p><code>%%user_pass%%</code> : This will be replaced with user password generated by the system.</p>
				<p><code>%%login_url%%</code> : This will be replaced with the login Url, you can wrap this in an anchor tag as well.</p>
				<p><code>%%site_name%%</code> : This will be replaced with your website name saved under General Settings.</p>
		',
		'suffix' => '',
		'prefix' => '',
		'default' => $cjsupport_email_messages['new_user_message_to_client'],
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	),
	array(
		'type' => 'submit',
		'id' => '',
		'label' => __('Save Settings', 'cjsupport'),
		'info' => '',
		'suffix' => '',
		'prefix' => '',
		'default' => '',
		'options' => '', // array in case of dropdown, checkbox and radio buttons
	),
);